"""
app/ai/providers/base.py
-------------------------
Base interface and exception definitions for AI inference providers.
"""

from __future__ import annotations

from abc import ABC, abstractmethod
from typing import Any


class AIProviderError(RuntimeError):
    """Base exception for provider failures."""
    pass


class AIProvider(ABC):

    @abstractmethod
    async def chat_completion(
        self,
        messages: list[dict[str, str]],
        temperature: float,
        max_tokens: int,
        response_format: dict[str, Any] | None = None,
        **kwargs: Any,
    ) -> str:
        """
        Execute chat completion using the model provider.

        Args:
            messages: List of chat messages (role, content).
            temperature: Sampling temperature.
            max_tokens: Limit on generated tokens.
            response_format: Optional dict specifying formatting (e.g. {"type": "json_object"}).

        Returns:
            The raw text content generated by the model.

        Raises:
            AIProviderError: If the call fails.
        """
        pass
